### ISSUE TITLE
Incorrect response serialize

### ISSUE THREAD

**Issue by mamsdeveloper** [MarcoMuellner/openapi-python-generator#18] opened 2023-02-24 07:27 UTC
**Describe the bug**
In response serialization `response.json()` called, but response is actually json object
```python
# ...
    async with aiohttp.ClientSession(headers=headers) as session:
        async with session.request(
            "get",
            base_path + path,
            params=query_params,
        ) as inital_response:
            if inital_response.status != 200:
                raise HTTPException(inital_response.status, f" failed with status code: {inital_response.status}")
            response = await inital_response.json() # response is json
            # another call of .json() for response raise AttributeError: 'dict' object has no attribute 'json'
            return UsersResponse(**response.json()) if response.json() is not None else UsersResponse()
```

**To Reproduce**
openapi-python-generator SOURCE OUTPUT --library aiohttp

**Comment by MarcoMuellner** [comment] 2023-02-24 07:58
Should be a duplicate of #15 , so lets move the discussion over there :)

**Closed by MarcoMuellner** 2023-02-24 07:58 UTC
